/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fofo.hmleditor;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author fofo
 */
public class HMLEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    public HMLEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jModelChoose = new javax.swing.JFileChooser();
        jDRealChoose = new javax.swing.JFileChooser();
        jDialogDReal = new javax.swing.JDialog();
        jPanelDReal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDRealPath = new javax.swing.JTextField();
        jButtonNavigateDReal = new javax.swing.JButton();
        jTextFieldPrecision = new javax.swing.JTextField();
        jButtonDefaultPrecision = new javax.swing.JButton();
        jCheckBoxODEParallel = new javax.swing.JCheckBox();
        jCheckBoxODECache = new javax.swing.JCheckBox();
        jCheckBoxDeltaHeuristic = new javax.swing.JCheckBox();
        jCheckBoxShortSat = new javax.swing.JCheckBox();
        jButtonCheckAll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldODEGrid = new javax.swing.JTextField();
        jPanelModel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaModel = new javax.swing.JTextArea();
        jPanelOutput = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBarHML = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuConfig = new javax.swing.JMenu();
        jMenuItemSelectDreal = new javax.swing.JMenuItem();

        jModelChoose.setAccessory(jMenuItemOpen);
        jModelChoose.setDialogTitle("HML Model");
        jModelChoose.setFileFilter(new HMLCustomFilter());

        jDRealChoose.setDialogTitle("select dReal ");

        jDialogDReal.setTitle("dReal");
        jDialogDReal.setMinimumSize(new java.awt.Dimension(700, 200));
        jDialogDReal.setPreferredSize(new java.awt.Dimension(700, 200));

        jLabel1.setText("Path:");

        jLabel2.setText("Precision:");

        jTextFieldDRealPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDRealPathActionPerformed(evt);
            }
        });

        jButtonNavigateDReal.setText("Navigate");
        jButtonNavigateDReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavigateDRealActionPerformed(evt);
            }
        });

        jTextFieldPrecision.setText("0.001");
        jTextFieldPrecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecisionActionPerformed(evt);
            }
        });

        jButtonDefaultPrecision.setText("Default");
        jButtonDefaultPrecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefaultPrecisionActionPerformed(evt);
            }
        });

        jCheckBoxODEParallel.setText("ODE Parallel");
        jCheckBoxODEParallel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxODEParallelActionPerformed(evt);
            }
        });

        jCheckBoxODECache.setText("ODE Cache");

        jCheckBoxDeltaHeuristic.setText("Delta Heuristic");

        jCheckBoxShortSat.setText("Short Sat");

        jButtonCheckAll.setText("Check All");
        jButtonCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckAllActionPerformed(evt);
            }
        });

        jLabel3.setText("ODE Grid:");

        jTextFieldODEGrid.setText("1024");

        javax.swing.GroupLayout jPanelDRealLayout = new javax.swing.GroupLayout(jPanelDReal);
        jPanelDReal.setLayout(jPanelDRealLayout);
        jPanelDRealLayout.setHorizontalGroup(
            jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDRealLayout.createSequentialGroup()
                        .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDRealPath)
                            .addComponent(jTextFieldPrecision, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(jTextFieldODEGrid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDRealLayout.createSequentialGroup()
                        .addComponent(jCheckBoxODEParallel)
                        .addGap(42, 42, 42)
                        .addComponent(jCheckBoxODECache)
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBoxDeltaHeuristic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jCheckBoxShortSat)
                        .addGap(26, 26, 26)))
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCheckAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNavigateDReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDefaultPrecision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDRealLayout.setVerticalGroup(
            jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDRealPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNavigateDReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDefaultPrecision)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldODEGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxODEParallel)
                    .addComponent(jCheckBoxODECache)
                    .addComponent(jCheckBoxDeltaHeuristic)
                    .addComponent(jCheckBoxShortSat)
                    .addComponent(jButtonCheckAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogDRealLayout = new javax.swing.GroupLayout(jDialogDReal.getContentPane());
        jDialogDReal.getContentPane().setLayout(jDialogDRealLayout);
        jDialogDRealLayout.setHorizontalGroup(
            jDialogDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jDialogDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogDRealLayout.createSequentialGroup()
                    .addGap(0, 38, Short.MAX_VALUE)
                    .addComponent(jPanelDReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 38, Short.MAX_VALUE)))
        );
        jDialogDRealLayout.setVerticalGroup(
            jDialogDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jDialogDRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogDRealLayout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(jPanelDReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelModel.setBorder(javax.swing.BorderFactory.createTitledBorder("Model"));

        jTextAreaModel.setColumns(20);
        jTextAreaModel.setRows(5);
        jScrollPane1.setViewportView(jTextAreaModel);

        javax.swing.GroupLayout jPanelModelLayout = new javax.swing.GroupLayout(jPanelModel);
        jPanelModel.setLayout(jPanelModelLayout);
        jPanelModelLayout.setHorizontalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        jPanelModelLayout.setVerticalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        jPanelOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        jTextArea2.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanelOutputLayout = new javax.swing.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);
        jMenuFile.add(jSeparator1);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBarHML.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBarHML.add(jMenuEdit);

        jMenuConfig.setText("Config");

        jMenuItemSelectDreal.setText("dReal");
        jMenuItemSelectDreal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectDrealActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItemSelectDreal);

        jMenuBarHML.add(jMenuConfig);

        setJMenuBar(jMenuBarHML);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        int returnVal = jModelChoose.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jModelChoose.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          jTextAreaModel.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

     class HMLCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".hml" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".hml");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.hml)";
        }
    } 
    
    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSelectDrealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectDrealActionPerformed
           jDialogDReal.setVisible(true);
           jDialogDReal.setLocationRelativeTo(this);
            
    }//GEN-LAST:event_jMenuItemSelectDrealActionPerformed

    private void jTextFieldDRealPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDRealPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDRealPathActionPerformed

    private void jButtonNavigateDRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavigateDRealActionPerformed
         int returnVal = jDRealChoose.showOpenDialog(this);
         if (returnVal == JFileChooser.APPROVE_OPTION) {            
            File file = jDRealChoose.getSelectedFile();      
              // What to do with the file, e.g. display it in a TextArea
                jTextFieldDRealPath.setText(file.getAbsolutePath());                  
            } else {
                System.out.println("File access cancelled by user.");
            }         
        jDialogDReal.setVisible(true);
    }//GEN-LAST:event_jButtonNavigateDRealActionPerformed

    private void jTextFieldPrecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecisionActionPerformed

    private void jCheckBoxODEParallelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxODEParallelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxODEParallelActionPerformed

    private void jButtonCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckAllActionPerformed
            jCheckBoxDeltaHeuristic.setSelected(true);
            jCheckBoxODECache.setSelected(true);
            jCheckBoxODEParallel.setSelected(true);
            jCheckBoxShortSat.setSelected(true);
    }//GEN-LAST:event_jButtonCheckAllActionPerformed

    private void jButtonDefaultPrecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefaultPrecisionActionPerformed
        if (jTextFieldPrecision.getText().equals("-1")) {
            jTextFieldPrecision.setBackground(Color.white);
            jTextFieldPrecision.setEditable(true);
        } else {
            jTextFieldPrecision.setText("-1");
             jTextFieldPrecision.setBackground(Color.gray);
            jTextFieldPrecision.setEditable(false);
        }
    }//GEN-LAST:event_jButtonDefaultPrecisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMLEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMLEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMLEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMLEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMLEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckAll;
    private javax.swing.JButton jButtonDefaultPrecision;
    private javax.swing.JButton jButtonNavigateDReal;
    private javax.swing.JCheckBox jCheckBoxDeltaHeuristic;
    private javax.swing.JCheckBox jCheckBoxODECache;
    private javax.swing.JCheckBox jCheckBoxODEParallel;
    private javax.swing.JCheckBox jCheckBoxShortSat;
    private javax.swing.JFileChooser jDRealChoose;
    private javax.swing.JDialog jDialogDReal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBarHML;
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSelectDreal;
    private javax.swing.JFileChooser jModelChoose;
    private javax.swing.JPanel jPanelDReal;
    private javax.swing.JPanel jPanelModel;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaModel;
    private javax.swing.JTextField jTextFieldDRealPath;
    private javax.swing.JTextField jTextFieldODEGrid;
    private javax.swing.JTextField jTextFieldPrecision;
    // End of variables declaration//GEN-END:variables
}
